apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
    build: "5"
  name: {{ .Values.app.name }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
